version: "3.7"
services:

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    image: keeganlandrigan/ubyssey-dev-db:0.0.1
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_USER: root
      MYSQL_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20

## Starts up Django server for ubyssey.ca
  django:
    image: keeganlandrigan/ubyssey.ca:latest
    volumes:
      - .:/ubyssey.ca/tmp
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      GOOGLE_APPLICATION_CREDENTIALS: somecredentials
    ports:
      - "8000:8000"
      - "4444:4444"
    depends_on:
      - db
    stdin_open: true
    tty: true


volumes:
  data: {}
